services:
  - type: web
    name: btech-event-hub-backend
    env: node
    plan: free
    startCommand: cd backend && npm install && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3000
